# Config file for automatic testing at travis-ci.org

language: python
python:
  - "2.7"
  - "3.7"

install:
  - wget https://repo.anaconda.com/pkgs/misc/conda-execs/conda-latest-linux-64.exe -O conda.exe
  - chmod +x conda.exe
  - export CONDA_ALWAYS_YES=1
  - ./conda.exe create -p $HOME/miniconda python=$TRAVIS_PYTHON_VERSION conda conda-build pytest six pytest-cov pytest-mock
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda build conda.recipe --no-test
  - conda install --use-local conda-prefix-replacement
script:
  - pytest -v --color=yes --cov=cpr tests
after_success:
  - conda install codecov
  - codecov
